version: "3"
services:
  node7:
    image: "node:7"
    user: "node"
    working_dir: /home/node/app
    environment:
      DB_URL: 'mongodb://db:27018'
      NODE_ENV: "development"
      DBWEBB_PORT: "8080"
    volumes:
      - ./:/home/node/app
    ports:
      - "1337:8080"
    command: "yarn start"

  node8:
    image: "node:8"
    user: "node"
    working_dir: /home/node/app
    environment:
      DB_URL: 'mongodb://db:27018'
      NODE_ENV: "development"
      DBWEBB_PORT: "8080"
    volumes:
      - ./:/home/node/app
    ports:
      - "1338:8080"
    command: "yarn start"

  node9:
    image: "node:9"
    user: "node"
    working_dir: /home/node/app
    environment:
      DB_URL: 'mongodb://db:27018'
      NODE_ENV: "development"
      DBWEBB_PORT: "8080"
    volumes:
      - ./:/home/node/app
    ports:
      - "1339:8080"
    command: "yarn start"

  node_alpine:
    build:
        context: .
        dockerfile: docker/Dockerfile-node-alpine
    environment:
      DB_URL: 'mongodb://db:27018'
    volumes:
      - ./:/app/
      - /app/node_modules/
    ports:
      - "8080:8080"
    command: "yarn start"

  development:
    image: "node:9"
    user: "node"
    working_dir: /home/node/app
    environment:
      DB_URL: 'mongodb://db:27018'
      NODE_ENV: "development"
      DBWEBB_PORT: "8080"
    volumes:
      - ./:/home/node/app
    ports:
      - "8080:8080"
    command: "yarn start"

  db:
    image: "mongo"
    container_name: "mongodb"
    ports:
      - "27018:27018"
    command: mongod --port 27018 --bind_ip_all

  backend:
    image: "node:9"
    user: "node"
    working_dir: /home/node/app
    environment:
      DB_URL: 'mongodb://db:27018'
      NODE_ENV: "production"
      DBWEBB_PORT: "8080"
    volumes:
      - ./:/home/node/app
    ports:
      - "8080:8080"
    command: "yarn start:production"
